
ALTER TABLE bonds DROP CONSTRAINT IF EXISTS name_max_length;
ALTER TABLE bonds DROP CONSTRAINT IF EXISTS name_min_length;

ALTER TABLE bonds DROP CONSTRAINT IF EXISTS bond_max;
ALTER TABLE bonds DROP CONSTRAINT IF EXISTS bond_min;

ALTER TABLE bonds DROP CONSTRAINT IF EXISTS price_min;
ALTER TABLE bonds DROP CONSTRAINT IF EXISTS price_max;

ALTER TABLE bonds DROP CONSTRAINT IF EXISTS foreign_key_issuer;
