
ALTER TABLE bonds DROP CONSTRAINT  name_max_length;
ALTER TABLE bonds DROP CONSTRAINT  name_min_length;

ALTER TABLE bonds DROP CONSTRAINT  bond_max;
ALTER TABLE bonds DROP CONSTRAINT  bond_min;

ALTER TABLE bonds DROP CONSTRAINT price_min;
ALTER TABLE bonds DROP CONSTRAINT price_max;

ALTER TABLE bonds DROP CONSTRAINT fk_owner_id;
ALTER TABLE bonds DROP CONSTRAINT fk_created_by;